### ISSUE TITLE
ModuleNotFoundError: No module named 'methylcheck.probes'

### ISSUE THREAD

**Issue by moqri** [FOXOBioScience/methylprep#50]
![Capture](https://user-images.githubusercontent.com/4342458/76531133-c1302b00-6442-11ea-92b3-882da57be344.JPG)

**Comment by marcmaxson** [comment]
@moqri is this still an issue? 

Here is what I get from latest version (0.4.0)

```
>>> import methylcheck
>>> methylcheck.probes
<module 'methylcheck.probes' from '/Users/mmaxmeister/methylcheck/methylcheck/probes/__init__.py'>
```

We moved files around in 0.4.0 compared to earlier versions, so please upgrade. 
And thanks for alerting us to any bugs.

**Comment by marcmaxson** [comment]
Also worth noting: you submitted this issue on methylprep but it refers to methylcheck.

**Comment by marcmaxson** [comment]
@moqri I'm addressing github issues for methylprep this week. Does this bug still appear in the latest version of methylcheck? We are on version 0.6.1 now.
